

services:
  web:
    build: .
    container_name: django_app
    env_file:
      - .env 
    command: >
      sh -c "python manage.py migrate &&
             gunicorn webapp.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - .:/app

    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTING_MODULE: webapp.settings
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "10516:8000"   # ← expose port web container เป็น 10516 บน host

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"        # ← map port host 80 → container 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: myproject_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
